// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"niceBackend/internal/repository/db_repo/categroy_repo"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newCategory(db *gorm.DB) category {
	_category := category{}

	_category.categoryDo.UseDB(db)
	_category.categoryDo.UseModel(&categroy_repo.Category{})

	tableName := _category.categoryDo.TableName()
	_category.ALL = field.NewField(tableName, "*")
	_category.ID = field.NewUint(tableName, "id")
	_category.CreatedAt = field.NewTime(tableName, "created_at")
	_category.UpdatedAt = field.NewTime(tableName, "updated_at")
	_category.DeletedAt = field.NewField(tableName, "deleted_at")
	_category.UUID = field.NewField(tableName, "_id")
	_category.Pid = field.NewUint32(tableName, "pid")
	_category.Name = field.NewString(tableName, "name")
	_category.Slug = field.NewString(tableName, "slug")
	_category.Description = field.NewString(tableName, "description")
	_category.IconName = field.NewString(tableName, "icon_name")
	_category.IconValue = field.NewString(tableName, "icon_value")
	_category.Extends = field.NewString(tableName, "extends")

	_category.fillFieldMap()

	return _category
}

type category struct {
	categoryDo categoryDo

	ALL         field.Field
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	UUID        field.Field
	Pid         field.Uint32
	Name        field.String
	Slug        field.String
	Description field.String
	IconName    field.String
	IconValue   field.String
	Extends     field.String

	fieldMap map[string]field.Expr
}

func (c category) Table(newTableName string) *category {
	c.categoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c category) As(alias string) *category {
	c.categoryDo.DO = *(c.categoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *category) updateTableName(table string) *category {
	c.ALL = field.NewField(table, "*")
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.UUID = field.NewField(table, "_id")
	c.Pid = field.NewUint32(table, "pid")
	c.Name = field.NewString(table, "name")
	c.Slug = field.NewString(table, "slug")
	c.Description = field.NewString(table, "description")
	c.IconName = field.NewString(table, "icon_name")
	c.IconValue = field.NewString(table, "icon_value")
	c.Extends = field.NewString(table, "extends")

	c.fillFieldMap()

	return c
}

func (c *category) WithContext(ctx context.Context) *categoryDo { return c.categoryDo.WithContext(ctx) }

func (c category) TableName() string { return c.categoryDo.TableName() }

func (c *category) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *category) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["_id"] = c.UUID
	c.fieldMap["pid"] = c.Pid
	c.fieldMap["name"] = c.Name
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["description"] = c.Description
	c.fieldMap["icon_name"] = c.IconName
	c.fieldMap["icon_value"] = c.IconValue
	c.fieldMap["extends"] = c.Extends
}

func (c category) clone(db *gorm.DB) category {
	c.categoryDo.ReplaceDB(db)
	return c
}

type categoryDo struct{ gen.DO }

func (c categoryDo) Debug() *categoryDo {
	return c.withDO(c.DO.Debug())
}

func (c categoryDo) WithContext(ctx context.Context) *categoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoryDo) Clauses(conds ...clause.Expression) *categoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoryDo) Returning(value interface{}, columns ...string) *categoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoryDo) Not(conds ...gen.Condition) *categoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoryDo) Or(conds ...gen.Condition) *categoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoryDo) Select(conds ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoryDo) Where(conds ...gen.Condition) *categoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *categoryDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c categoryDo) Order(conds ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoryDo) Distinct(cols ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoryDo) Omit(cols ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoryDo) Join(table schema.Tabler, on ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *categoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *categoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoryDo) Group(cols ...field.Expr) *categoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoryDo) Having(conds ...gen.Condition) *categoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoryDo) Limit(limit int) *categoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoryDo) Offset(offset int) *categoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoryDo) Unscoped() *categoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categoryDo) Create(values ...*categroy_repo.Category) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoryDo) CreateInBatches(values []*categroy_repo.Category, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoryDo) Save(values ...*categroy_repo.Category) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoryDo) First() (*categroy_repo.Category, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*categroy_repo.Category), nil
	}
}

func (c categoryDo) Take() (*categroy_repo.Category, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*categroy_repo.Category), nil
	}
}

func (c categoryDo) Last() (*categroy_repo.Category, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*categroy_repo.Category), nil
	}
}

func (c categoryDo) Find() ([]*categroy_repo.Category, error) {
	result, err := c.DO.Find()
	return result.([]*categroy_repo.Category), err
}

func (c categoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*categroy_repo.Category, err error) {
	buf := make([]*categroy_repo.Category, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoryDo) FindInBatches(result *[]*categroy_repo.Category, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoryDo) Attrs(attrs ...field.AssignExpr) *categoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoryDo) Assign(attrs ...field.AssignExpr) *categoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoryDo) Joins(field field.RelationField) *categoryDo {
	return c.withDO(c.DO.Joins(field))
}

func (c categoryDo) Preload(field field.RelationField) *categoryDo {
	return c.withDO(c.DO.Preload(field))
}

func (c categoryDo) FirstOrInit() (*categroy_repo.Category, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*categroy_repo.Category), nil
	}
}

func (c categoryDo) FirstOrCreate() (*categroy_repo.Category, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*categroy_repo.Category), nil
	}
}

func (c categoryDo) FindByPage(offset int, limit int) (result []*categroy_repo.Category, count int64, err error) {
	if limit <= 0 {
		count, err = c.Count()
		return
	}

	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c *categoryDo) withDO(do gen.Dao) *categoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
