// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdministrator = "tb_administrator"

// Administrator mapped from table <tb_administrator>
type Administrator struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UID       string         `gorm:"column:uid" json:"uid"`
	Account   string         `gorm:"column:account;not null" json:"account"`
	Password  string         `gorm:"column:password" json:"password"`
	NickName  string         `gorm:"column:nick_name" json:"nick_name"`
	HeaderImg string         `gorm:"column:header_img;default:http://qmplusimg.henrongyi.top/head.png" json:"header_img"` // 用户头像
	Email     string         `gorm:"column:email" json:"email"`
	Phone     string         `gorm:"column:phone" json:"phone"`
	Company   string         `gorm:"column:company" json:"company"`
	Address   string         `gorm:"column:address" json:"address"`
	Remark    string         `gorm:"column:remark" json:"remark"`
	Status    int32          `gorm:"column:status;default:0" json:"status"`
}

// TableName Administrator's table name
func (*Administrator) TableName() string {
	return TableNameAdministrator
}
